'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default
    
    '''<summary>
    '''tbleInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbleInfo As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''tblePIDzoek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblePIDzoek As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''txtZoekPID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtZoekPID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbListStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbListStatus As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rbListFormulier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbListFormulier As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''cbxinclusiefPlantoelichting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxinclusiefPlantoelichting As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''tbleContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbleContent As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''tbleResultaten control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbleResultaten As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''grdResultaten control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdResultaten As Global.System.Web.UI.WebControls.GridView
End Class
