'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Desktop
    
    '''<summary>
    '''head control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents head As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''frmMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmMain As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''cphTopMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cphTopMenu As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''tbleTopMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbleTopMenu As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''EGMlogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EGMlogo As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lnkSigaal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSigaal As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkKlachten control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkKlachten As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkStartEvaluatie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkStartEvaluatie As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkBeoordeling control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkBeoordeling As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkAudits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAudits As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''Archief control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Archief As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkAdministratie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAdministratie As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cphBigImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cphBigImage As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''cphInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cphInfo As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''cphContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cphContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''cphFooter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cphFooter As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
