'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Projectlifecycle
    
    '''<summary>
    '''tbleBigImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbleBigImage As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''titelProject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents titelProject As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''titelIntroPlantoelichting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents titelIntroPlantoelichting As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbleInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbleInfo As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''lnkProjectAlgemeen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkProjectAlgemeen As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkProjectIntern control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkProjectIntern As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkProjectExtern control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkProjectExtern As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkProjectIntranet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkProjectIntranet As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkProjectKosten control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkProjectKosten As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkProjectKengetallen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkProjectKengetallen As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkProjectGebouwSpecificaties control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkProjectGebouwSpecificaties As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkProjectAudits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkProjectAudits As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkProjectWerkderden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkProjectWerkderden As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkProjectKlachten control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkProjectKlachten As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkProjectDuurzaamheid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkProjectDuurzaamheid As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkProjectStartbijeenkomst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkProjectStartbijeenkomst As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkProjectEvaluatiebijeenkomst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkProjectEvaluatiebijeenkomst As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkProjectBIM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkProjectBIM As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lifecycleCell0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lifecycleCell0 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lifecycleCell1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lifecycleCell1 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lifecycleCell2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lifecycleCell2 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lifecycleCell3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lifecycleCell3 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lifecycleCell4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lifecycleCell4 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lifecycleCell5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lifecycleCell5 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''tbleProjectAlgemeen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbleProjectAlgemeen As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''lblRoepnaam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRoepnaam As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblWijkPlangebied control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWijkPlangebied As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblExterneNaam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExterneNaam As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAdres control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdres As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblClusternaam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClusternaam As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPostcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPostcode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCommercieleNaam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCommercieleNaam As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPlaats control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlaats As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCommercieleNaamUK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCommercieleNaamUK As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLand As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblStatusProject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatusProject As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMarktcategorie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMarktcategorie As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblProjectFase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProjectFase As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCommercieleCategorie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCommercieleCategorie As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDatumProspect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDatumProspect As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblProspectnummer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProspectnummer As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblProjectSoort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProjectSoort As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDatumProject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDatumProject As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblOpdrachtsoort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOpdrachtsoort As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblVervolgOp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVervolgOp As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblVerwervingswijze control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVerwervingswijze As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblOpdrachtsom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOpdrachtsom As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblHonorariumafspraak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHonorariumafspraak As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPlantoelichting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlantoelichting As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblProjectSpecificaties control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProjectSpecificaties As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblOntwerpenStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOntwerpenStart As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblOntwerpenEind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOntwerpenEind As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblEerstePaal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEerstePaal As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSOstart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSOstart As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSOeind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSOeind As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblHoogstePunt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHoogstePunt As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblVOstart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVOstart As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblVOeind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVOeind As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblOpleverdatum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOpleverdatum As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDOstart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOstart As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDOeind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOeind As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblOpening control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOpening As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTechnischOntwerpStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTechnischOntwerpStart As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTechnischOntwerpEind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTechnischOntwerpEind As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblUitvoeringStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUitvoeringStart As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblUitvoeringEind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUitvoeringEind As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbleProjectIntern control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbleProjectIntern As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''lblTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTeam As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblGroep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGroep As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblProjectArchitect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProjectArchitect As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblGroepsManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGroepsManager As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblProjectCoordinator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProjectCoordinator As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblGroepsArchitect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGroepsArchitect As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBewaker1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBewaker1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBewaker2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBewaker2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblArchitectenOntwerpers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblArchitectenOntwerpers As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblInterieurArchitecten control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInterieurArchitecten As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCoordinatoren control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCoordinatoren As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPersoonsprofielen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPersoonsprofielen As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblProjectteam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProjectteam As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbleProjectKengetallen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbleProjectKengetallen As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''lblTerreinOppervlakte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTerreinOppervlakte As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBVOalgemeneVoorzieningen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBVOalgemeneVoorzieningen As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBebouwdTerreinOppervlakte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBebouwdTerreinOppervlakte As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBVOeenheden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBVOeenheden As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBrutoInhoud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBrutoInhoud As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNettoInhoud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNettoInhoud As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBVO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBVO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNVO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNVO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAantalParkeerplaatsen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAantalParkeerplaatsen As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblGebruikersoppervlakte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGebruikersoppervlakte As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAantalBouwlagen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAantalBouwlagen As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblVerhuurbareOppervlakte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVerhuurbareOppervlakte As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblGebouwhoogte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGebouwhoogte As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblparkeerOppervlakte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblparkeerOppervlakte As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblGevelOppervlakte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGevelOppervlakte As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBeganegrondOppervlakte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBeganegrondOppervlakte As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDakOppervlakte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDakOppervlakte As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFloorSpaceIndex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFloorSpaceIndex As Global.System.Web.UI.WebControls.Label
End Class
